In [1]:
import numpy as np

In [2]:
A=np.array([[2,1],[1,2]])
x=np.array([3,4])
np.matmul(A,x)
y=np.array([1,2])

np.matmul(y,np.matmul(A,x))

A=np.array([[2,1],[20,2]])
np.linalg.norm(A,np.inf)
np.linalg.norm(x,np.inf)

4.0

In [3]:
def powerMethod(A,x0,tol):
  x=x0
  lambd= np.matmul(x,np.matmul(A,x))/np.matmul(x,x)

  lambdOld=lambd+1
  count=0
  while np.abs(lambd-lambdOld) > tol:
    count+=1
    if count >= 100:
      print('Too many iterations!')
      return

    y=np.matmul(A,x)
    x=y/np.linalg.norm(y,np.inf)

    lambdOld=lambd
    lambd = np.matmul(x,np.matmul(A,x))/np.matmul(x,x)

  return x, lambd

In [4]:
A=np.array([[2,1],[1,2]])
x=np.array([1,0])
powerMethod(A,x,1e-16)

(array([1., 1.]), 3.0)

In [5]:
V,D=np.linalg.eig(A)

In [6]:
V

array([3., 1.])

In [7]:
D

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [8]:
1/np.sqrt(2)

0.7071067811865475

In [9]:
A=np.array([[1,2,3],[4,5,6],[7,8,8]])
x=np.array([1,0,0])
powerMethod(A,x,1e-16)

(array([0.29983048, 0.68205866, 1.        ]), 15.55528260941108)